### ISSUE TITLE
How do I serialize an object with Multiple Relationships?

### ISSUE THREAD

**Issue by Kristof-Mattei** [jun-sheaf/ts-japi#1]
For example: 

Client with multiple buildings and multiple employees.

```typescript
const EmployeeSerializer = new Serializer('employees');

const EmployeeClientRelator = new Relator(
  async (client: Client) => client.employees,
  {
    serializer: EmployeeSerializer,
  }
);

const BuildingSerializer = new Serializer('buildings');

const BuildingClientRelator = new Relator(
  async (client: Client) => project.buildings,
  {
    serializer: BuildingSerializer
  }
);

const ClientSerializer = new Serializer('clients', {
  relator: ... // this only accepts 1 relator, not multiple
  // doesn't work[EmployeeClientRelator, BuildingClientRelator]; 
};
```

**Comment by jun-sheaf** [comment]
Thanks for the example.

So I have thought this over and I don't believe this should be a feature. The main reason being the API endpoint wouldn't be quite well-defined. To be precise, usually the approach is to send two requests (in your case, `/client/client_id/employees` and `/client/client_id/buildings`) and obtain the resources. Getting both resources at the same time would not manage well (and I cannot really think of a good url [perhaps `/client/client_id/employees_buildings`?]).

A solution could be using the above approach and at each endpoint, using the [`onlyRelationship`](https://jun-sheaf.github.io/ts-japi/interfaces/serializeroptions.html) override with a depth of 1 so only the desired data is sent rather than the client with the data.

**Comment by Kristof-Mattei** [comment]
So that seems contrary to what I understand from JSONApi:

https://jsonapi.org/format/#document-compound-documents

This means that this API doesn't support generating compound documents. 

The whole idea to query a `client` and retrieve a set of `employees` and a set of `buildings`, either included (as per the `?include=employees,buildings`), or just as a link.

**Comment by jun-sheaf** [comment]
I took a quick look at the `relationships` part of the documentation and found this tidbit

> Relationships may be to-one or to-many.

The "main problem" I thought about aside, I understand where your coming from. This wouldn't be that difficult to implement, so I'll get it done as soon as I can.

**Comment by Kristof-Mattei** [comment]
Well, I don't think the 'one-to-many' part here is the issue.

A 'one-to-one' is 'Country' to 'Capital City'. That you already support. A 'one-to-many' is Country to Cities, which you also support. 

But what's missing is a 'Country' to 'Cities' and a 'Country' to 'Capital City' in 1 call.

**Comment by jun-sheaf** [comment]
From what I understand, the one-to-many is from one type to many types, but it could also go your way. In honesty, the docs are a bit imprecise and there has been talk about improving it.

**Comment by jun-sheaf** [comment]
You can now use arrays of relators. Your example should exhibit a `buildings` and `employees` key within the `relationships` object.

Thanks for the issue.

**Comment by Kristof-Mattei** [comment]
@jun-sheaf I'll try it out.
